import Card from "@/src/component/card";
import SearchSection from "@/src/component/searchSection";
import React, { useState } from "react";
import { APP_ROUTES } from "@/src/utils/appRoutes";
import { useRouter } from "next/navigation";
import { solarData } from "@/src/hooks/electricals/solar/solarData";

const Solar = () => {
  const [data, setData] = useState(solarData);
  const router = useRouter();

  const handleClick = (id: string | undefined) => {
    router.push(`${APP_ROUTES.ELECTRICAL_PAGE}/solar/${id}`);
  };
  return (
    <div>
      <h1 className="my-6">
        A solar inverter serves as the backbone of solar energy systems,
        converting the DC (direct current) electricity generated by solar panels
        into AC (alternating current) electricity usable for homes and
        businesses. These inverters efficiently manage the power flow, ensuring
        compatibility with the electrical grid and enabling surplus energy to be
        exported back to the grid. Their role in maximizing energy production
        and facilitating seamless integration with the existing power
        infrastructure is critical in harnessing the potential of solar energy
        for sustainable power generation.
      </h1>
      <div>
        {/* <SearchSection /> */}
      </div>
      <section>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-6">
      {data.map((item, index) => (
            // eslint-disable-next-line react/jsx-key
            <Card
              src={item.src}
              title={item.title}
              text={item.buttonText}
              id={item?.id}
              onClick={() => handleClick(item?.id)}
            />
          ))}
        </div>
      </section>
    </div>
  );
};

export default Solar;
